// poc/web/angular/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html'
})
export class LoginComponent {
  loading = false;
  error: string | null = null;
  success = false;

  form = this.fb.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required, Validators.minLength(6)]],
  });

  constructor(private fb: FormBuilder, private auth: AuthService) { }

  submit() {
    if (this.form.invalid) return;
    this.loading = true;
    this.error = null;
    this.success = false;

    const { email, password } = this.form.getRawValue();
    this.auth.login({ email: email!, password: password! }).subscribe({
      next: () => {
        this.success = true;
        this.loading = false;
      },
      error: (err) => {
        this.loading = false;
        this.error = err?.error?.message || 'Login failed';
      },
    });
  }
}


<div class="min-h-screen bg-gray-50 flex items-center justify-center p-4">
  <div class="w-full max-w-md bg-white shadow-lg rounded-2xl p-6">
    <div class="mb-6 text-center">
      <h2 class="text-2xl font-semibold tracking-tight text-gray-900">Welcome back</h2>
      <p class="text-sm text-gray-600 mt-1">Sign in to continue</p>
    </div>

    <form (ngSubmit)="submit()" [formGroup]="form" class="space-y-4">
      <div>
        <label for="email" class="block text-sm font-medium text-gray-700">Email</label>
        <input
          id="email"
          type="email"
          formControlName="email"
          placeholder="you@example.com"
          class="mt-1 block w-full rounded-lg border border-gray-300 px-3 py-2 text-gray-900 shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
        />
        <div class="mt-1 text-sm text-red-600" *ngIf="form.controls.email.touched && form.controls.email.invalid">
          Enter a valid email address
        </div>
      </div>

      <div>
        <label for="password" class="block text-sm font-medium text-gray-700">Password</label>
        <input
          id="password"
          type="password"
          formControlName="password"
          placeholder="••••••••"
          class="mt-1 block w-full rounded-lg border border-gray-300 px-3 py-2 text-gray-900 shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
        />
        <div class="mt-1 text-sm text-red-600" *ngIf="form.controls.password.touched && form.controls.password.invalid">
          Minimum 6 characters
        </div>
      </div>

      <button
        type="submit"
        [disabled]="loading || form.invalid"
        class="w-full inline-flex justify-center items-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-white font-medium shadow hover:bg-blue-700 disabled:opacity-60 disabled:cursor-not-allowed transition"
      >
        {{ loading ? 'Signing in…' : 'Sign in' }}
      </button>

      <div class="text-sm text-gray-600 text-center">
        Don’t have an account?
        <a routerLink="/register" class="font-medium text-blue-700 hover:underline">Create one</a>
      </div>

      <div class="text-sm text-red-600" *ngIf="error">{{ error }}</div>
      <div class="text-sm text-green-700" *ngIf="success">Logged in! Cookies should be set by backend.</div>
    </form>
  </div>
</div>

// poc/web/nuxt/app/pages/login.vue
<script setup lang="ts">
const config = useRuntimeConfig()
const email = ref('')
const password = ref('')
const loading = ref(false)
const errorMsg = ref('')
const okMsg = ref('')
const router = useRouter()

const onSubmit = async () => {
  errorMsg.value = ''
  okMsg.value = ''
  loading.value = true
  try {
    const { error } = await useFetch('/auth', {
      baseURL: config.public.apiBase,
      method: 'POST',
      credentials: 'include',
      headers: { 'Content-Type': 'application/json' },
      body: { email: email.value, password: password.value }
    })
    if (error.value) {
      const status = (error.value as any)?.status || 0
      errorMsg.value = status === 401 ? 'Invalid credentials' : 'Login error'
      return
    }
    okMsg.value = 'Signed in'
    setTimeout(() => router.push('/'), 600)
  } catch (e) {
    errorMsg.value = 'Network error'
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <main class="mx-auto max-w-md px-6 py-10 md:px-8">
    <h1 class="text-2xl font-semibold">Sign in</h1>
    <form @submit.prevent="onSubmit" class="mt-4 grid gap-3">
      <label class="grid gap-1">
        <div class="text-sm font-medium text-gray-700">Email</div>
        <input
          v-model="email"
          type="email"
          required
          placeholder="yoursupercoolemail@example.com"
          class="block w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-gray-900 placeholder:text-gray-400 shadow-sm focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
      </label>
      <label class="grid gap-1">
        <div class="text-sm font-medium text-gray-700">Password</div>
        <input
          v-model="password"
          type="password"
          required
          minlength="8"
          placeholder="your super omega strong password"
          class="block w-full rounded-md border border-gray-300 bg-white px-3 py-2 text-gray-900 placeholder:text-gray-400 shadow-sm focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
      </label>
      <button
        :disabled="loading"
        class="mt-1 inline-flex items-center justify-center rounded-md bg-blue-600 px-4 py-2 text-white shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:opacity-60"
      >
        {{ loading ? 'Signing in…' : 'Sign in' }}
      </button>
      <p v-if="errorMsg" class="text-sm text-red-600">{{ errorMsg }}</p>
      <p v-if="okMsg" class="text-sm text-green-700">{{ okMsg }}</p>
    </form>

    <p class="mt-4 text-sm text-gray-700">
      No account?
      <NuxtLink to="/register" class="text-blue-600 hover:underline">Create an account</NuxtLink>
    </p>
  </main>
</template>
